name: Simple DevSecOps Pipeline for DVWA

on:
  push:
    branches:
      - main

jobs:
  # Step 1: Basic Security Scan
  security_scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up PHP environment (DVWA is a PHP app)
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Using PHP 8.0 for DVWA

      # Install necessary PHP extensions
      - name: Install PHP Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y php-mysql php-gd

      # Run Static Application Security Testing (SAST) with Semgrep
      - name: Run Static Security Scan (Semgrep)
        run: |
          pip install semgrep
          semgrep --config=auto .

  # Step 2: Basic Build and Test
  build:
    runs-on: ubuntu-latest
    needs: security_scan
    steps:
      # Checkout the code again
      - name: Checkout Code
        uses: actions/checkout@v2

      # Build DVWA (simply moving files to the web server directory in a real environment)
      - name: Build DVWA
        run: |
          echo "Building the DVWA application..."
          # Here, you'd usually deploy the PHP files to a server. For the sake of simplicity:
          echo "DVWA Build Complete!"

  # Step 3: Slack Notification (Optional)
  notify_slack:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Notify Slack on Failure
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"🚨 The DVWA Pipeline failed! Check GitHub Actions for details."}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
